
services:
  api:
    build: .
    image: dm-api:v1
    environment:
      - PORT=5000
      - DATABASE_URL: postgres://postgres:postgres@db:5432/ma_base
    ports:
      - "5000:5000"
    depends_on:
      - db
    

  swagger:
    image: swaggerapi/swagger-ui:5
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    ports:
      - "8080:8080"
    depends_on:
      - api

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ma_base
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: