
services:
  api:
    build: .
    image: dm-api:v1
    environment:
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - db
    

  swagger:
    image: swaggerapi/swagger-ui:v5.17.14
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    ports:
      - "8080:8080"
    depends_on:
      - api

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ma_base
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com     
      PGADMIN_DEFAULT_PASSWORD: admin             
    ports:
      - "5050:80"                                
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin    

volumes:
  db_data:
  pgadmin_data: